FROM golang:1.18 AS builder

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o server ./cmd/server

FROM alpine:latest
RUN apk --no-cache add ca-certificates
WORKDIR /root/
COPY --from=builder /app/server .
COPY deploy/local/run/rest-memory/data.json /root/data.json
ENV STORAGE_MEMORY_MONSTER_DATA_PATH=/root/data.json
EXPOSE 8080
CMD ["./server"]