FROM node:16-alpine as build-stage
WORKDIR /app
COPY cmd/client/package*.json ./
RUN npm install
COPY cmd/client/ .
RUN npm run build:production

FROM node:16-alpine as production-stage
WORKDIR /app
COPY --from=build-stage /app/dist /app
RUN npm install -g serve
EXPOSE 8080
CMD ["serve", "-s", "-l", "8080", "/app"]